name: font-unpacker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unpack bootROM glyphs
      run: |
        # retrieve one of the main bios file
        curl -LO https://github.com/japanese-cake/dc-bios/raw/main/retail/bootROM_v1.01d.bin
        # run the unpack command
        python font-unpacker.py ./bootROM_v1.01d.bin
        FNT_NAME=$(ls output/ | head -n 1)
        echo "fnt_name = $FNT_NAME" >> $GITHUB_ENV
    - name: Archive bootROM glyphs
      uses: actions/upload-artifact@v4
      with:
        name: bootROM-glyphs
        path: output/${{ env.fnt_name }}
        if-no-files-found: error
